set -s escape-time 10
set -s focus-events on

unbind C-b

set -g prefix C-a

set -g base-index 1
set -g pane-base-index 1

setw -g automatic-rename on

set -g status-interval 30

set -g set-titles on
set -g set-titles-string "#W"

set -g mouse on

set -g monitor-activity on
set -g visual-activity on

# Use vim keybindings in copy mode
setw -g mode-keys vi

bind C-c new-session

bind _ split-window -v
bind | split-window -h

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

unbind p
bind -r C-h previous-window

unbind n
bind -r C-l next-window

bind Tab last-window

bind > swap-pane -D # swap current pane with the next one
bind < swap-pane -U # swap current pane with the previous one

bind a send-prefix

set-option -g status-bg colour000
set-option -g status-fg colour007

set-option -g window-status-format ' #[dim]#I:#W#F'
set-option -g window-status-current-format '#[bold] #I:#W#F'

set -g status-left-length 1000
set -g status-left "#[fg=colour001,bold] #S "

set -g status-right-length 1000
set -g status-right "#[bold,dim]#(curl wttr.in?format=1) · #(date '+%a, %d %b %Y · %I:%M %p')"

bind r source-file ~/.tmux.conf \; display "tmux configuration reloaded"
